### ISSUE TITLE
(standard_in) 1: syntax error

### ISSUE THREAD

**Issue by darthmongo** [andresgongora/synth-shell-greeter#23]
**Describe the bug**
Installed the script on my laptop and everything works great.  Followed the same instructions on another machine and I'm getting "(standard_in) 1: syntax error" on the top two lines when I open my command shell, but no graphic 
![DeepinScreenshot_select-area_20200506092055](https://user-images.githubusercontent.com/37725288/81202191-18520800-8f7b-11ea-8432-86ee22faffd0.png)

**Expected behavior**
I should see the standard opening graphic in ASCII.

**Screenshots**
I've attached a screenshot.

**Comment by transmissionator** [comment]
I think this issue can be closed now since https://github.com/andresgongora/synth-shell-greeter/pull/27. If the sensors command produces an error then it should not attempt to get the CPU temperature.

**Comment by andresgongora** [comment]
@transmissionator There is also a second bug that produces the exact same error. We are working on it as well. It's related to floating point numbers that use either `.` or `,` depending on the locale.

**Comment by andresgongora** [comment]
Closing, as we think we have found the exact issue in #28
