### ISSUE TITLE
Synth Shell logo is broken

### ISSUE THREAD

**Issue by RealNagus** [andresgongora/synth-shell-greeter#34]
Hello,

I just installed synth shell from git and got a broken synth shell logo in the console with the default settings.

![image](https://user-images.githubusercontent.com/15063041/203760984-e7ecbdcf-02c1-49f8-a80b-8da82253c0bb.png)

It turns out that the ascii art has an unescaped backslash at the very end of line 18 in synth-shell-greeter.config.default. If I replace it with a double backslash the logo is displayed just fine.

![image](https://user-images.githubusercontent.com/15063041/203760958-a08691bf-57cf-4b21-9ae0-703f42cfe4e0.png)

**Comment by andresgongora** [comment]
Wops! Good catch! This should be fixed as per c4afc44. I'll push it as soon as I can into the synth-shell main repo :)
Thanks!

**Comment by andresgongora** [comment]
It's odd though. I see you are on a debian machine. Didn't the setup script apply the `synth-shell-greeter.debian.config` configuration? Or did you override it with the default theme? The setup process is meant to detect some common OSs and apply a different theme with the appropriate logo. In your case it should look something like this :

```
logo="       _,met\$\$\$\$\$gg.
    ,g\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$P.
  ,g\$\$P\"\"       \"\"\"Y\$\$.\".
 ,\$\$P'              \`\$\$\$.
',\$\$P       ,ggs.     \`\$\$b:
\`d\$\$'     ,\$P\"'   .    \$\$\$
 \$\$P      d\$'     ,    \$\$P
 \$\$:      \$\$.   -    ,d\$\$'
 \$\$;      Y\$b._   _,d\$P'
 Y\$\$.    \`.\`\"Y\$\$\$\$P\"'
 \`\$\$b      \"-.__
 \`Y\$\$b
  \`Y\$\$.
    \`\$\$b.
      \`Y\$\$b.
        \`\"Y\$b._
            \`\"\"\"\"\n"
```

Note: ingore all the escape characters, it looks nice and tidy when displayed in the terminal ;)

**Comment by RealNagus** [comment]
The setup.sh didn't install the debian logo directly. Didn't know it was supposed to so I just had a look around for it and activated it manually. It does look nice. :-)

The /etc/os-release file in Debian 11 has a `VERSION_ID="11"` line, prior to `ID=debian`, so it erroneously ends up in the `$DISTRO` variable. If I replace the grep regexp with `... | grep "^ID=" | ...` in the setup script it seems to work fine and actually return "debian".

**Comment by andresgongora** [comment]
I was about to add your patch to the script, but if you like, why don't you create a pull request. I'd be happy having you as a contributor in the project. If not, just let me know and I'll add your suggestion directly ;)

**Comment by andresgongora** [comment]
Oh yeah, if you create a pull-request, don't be alarmed that there is no `develop` branch. Since this is a very small project and a git-submodule on top, I've found no need for it and I solve all bigger conflicts in the _parent_ synth-shell project instead

**Comment by RealNagus** [comment]
Hope I didn't mess up the pull request. Seems a bit overkill for literally just a single added character, but why not. ;)

**Comment by andresgongora** [comment]
Awesome! Just remember. $1 for tightening the screw, $999 for knowing what screw to check ;)
